#' Get the kelp status for a particular year
#'
#' @description
#' Status is calculated by dividing the given year's kelp area by the historical median across 1984-2013
#' for each kelp segment.
#'
#' @param annual_time_series Annual time series generated by [KelpAreaIndicator::extract_time_series()].
#' Does not work with quarterly time series
#' @param kelp_presence Kelp presence data frame generated by [KelpAreaIndicator::get_kelp_presence()]
#' @inheritParams rlang::args_dots_empty
#' @param status_year Year to calculate the status for, or `NULL` for the latest year in the time series.
#' Must be later than 2013
#' @param segment_id A character vector containing the subset of `segment_id`'s of interest, e.g.
#' `c("CA_71", "CA_78")`, or `NULL` for all segment IDs (default).
#'
#' @return A data frame with statuses for each Segment_ID in `annual_time_series`. A value of -999
#' indicates that there is not enough data to determine a status for the given kelp segment
#' @export
get_kelp_status <- function(
    annual_time_series,
    kelp_presence,
    ...,
    status_year = NULL,
    segment_id = NULL) {

  rlang::check_dots_empty()

  # if a segment_id or subset of segment_id's are specified, make sure
  # that they are all in the kelp_segments shapefile
  if (!is.null(segment_id)) {
    if (!all(segment_id %in% annual_time_series$Segment_ID)) {
      stop("not all values in `segment_id` are present in the annual time series")
    }
    annual_time_series <- annual_time_series |>
      dplyr::filter(Segment_ID %in% segment_id)
  }
  if ("quarter" %in% names(annual_time_series)) {
    stop("can only compute kelp status for the annualized time series")
  }
  if (is.null(status_year)) {
    status_year <- max(annual_time_series$year)
  }
  if (status_year <= 2013) {
    stop("`status_year` must be later than 2013")
  }

  kelp_status <- annual_time_series |>
    dplyr::inner_join(kelp_presence, by = "Segment_ID") |>
    dplyr::group_by(Segment_ID, presence, historical_med) |>
    dplyr::summarize(
      status = area_abs[year == status_year] / historical_med[year == status_year] * 100
    ) |>
    dplyr::mutate(
      year = status_year,
      status = ifelse(presence != 'Kelp', -999, status)
    ) |>
    dplyr::ungroup() |>
    dplyr::select(Segment_ID, year, status)

  kelp_status
}
