#' Calculate recent trends from annual kelp area time series
#'
#' @param annual_time_series Annual time series generated by [KelpAreaIndicator::extract_time_series()].
#' Does not work with quarterly time series
#' @inheritParams rlang::args_dots_empty
#' @param ref_year Reference year or years from which to calculate the recent trend. Years
#' included in the recent trend are `ref_year - num_years`, inclusive
#' @param num_recent_years Number of years before `ref_year` to include in recent trend
#'
#' @returns A data frame with the recent trend calculated by `Segment_ID` and `ref_year`.
#' If `ref_year` is a vector of years, then all recent trend data is collected into a single
#' dataframe in long format with columns for `Segment_ID`, `year`, `cumulative_coverage`,
#' and `delta`
#' @export
get_recent_trend <- function(annual_time_series, ..., ref_year = NULL, num_recent_years = 5) {
  rlang::check_dots_empty()

  if (is.null(ref_year)) {
    ref_year <- max(annual_time_series$year)
  }

  lapply(ref_year, function(y) {
    annual_time_series |>
      dplyr::filter(
        year >= min(c(max(year), y)) - num_recent_years,
        year <= y,
        .by = "Segment_ID"
      ) |>
      dplyr::group_by(Segment_ID) |>
      dplyr::arrange(year, .by_group = TRUE) |>
      dplyr::mutate(
        cumu_annual_change = area_abs - dplyr::lag(area_abs)
      ) |>
      dplyr::summarize(
        cumulative_coverage = sum(area_abs, na.rm = TRUE),
        delta = sum(cumu_annual_change, na.rm = TRUE) / sum(area_abs, na.rm = TRUE)
      ) |>
      dplyr::mutate(year = y)
  }) |>
    dplyr::bind_rows()
}
