#' Plot the given kelp area time series
#'
#' @param kelp_area_time_series Data frame generated by [KelpAreaIndicator::annualize_time_series()]
#' @param ... additional aesthetics passed to the ggplot call
#' @param type The type of representation for the area value. One of:
#' * "absolute": absolute value of the kelp area, in km^2
#' * "percent": kelp area relative to the maximum occupiable area, expressed as a percentage
#' * "historical": kelp area relative to the historical median, expressed as a percentage
#' @param segment_id The segment ID to plot
#'
#' @return ggplot object for the time series
#' @export
plot_time_series <- function(
    kelp_area_time_series,
    ...,
    type = c("absolute", "percent", "historical"),
    segment_id = "CA_78") {
  type <- rlang::arg_match(type)
  if (length(segment_id) > 1) {
    stop("only one `segment_id` may be plotted at once")
  } else if (!segment_id %in% kelp_area_time_series$Segment_ID) {
    stop("`segment_id` not present in `kelp_area_time_series`")
  }

  kelp_area_time_series <- kelp_area_time_series |>
    dplyr::filter(Segment_ID %in% segment_id)

  plot_data <- kelp_area_time_series |>
    dplyr::mutate(
      y_val = switch(type,
        absolute = area_abs,
        percent = area_pct,
        historical = area_hist
      )
    )

  y_lab <- switch(type,
    absolute = expression(paste("Kelp Area ", (km^2))),
    percent = "% of Max Occupiable Area",
    historical = "% of Historical Median"
  )

  year_breaks <- min(kelp_area_time_series$year):max(kelp_area_time_series$year)
  ggplot2::ggplot(plot_data, ggplot2::aes(x = year, y = y_val, ...)) +
    ggplot2::geom_line() +
    ggplot2::scale_x_continuous(breaks = year_breaks) +
    ggplot2::labs(y = y_lab, x = "Year", title = paste("Segment", segment_id)) +
    ggplot2::theme_bw() +
    ggplot2::theme(
      panel.grid.minor = ggplot2::element_blank(),
      panel.grid.major.x = ggplot2::element_blank(),
      axis.text.x = ggplot2::element_text(angle = 60, vjust = 1, hjust = 1),
      legend.position = "inside",
      legend.position.inside = c(0.85, 0.85),
      legend.box.background = ggplot2::element_rect(color = "black")
    )
}
